### ISSUE TITLE
Addon not showing in addons list

### ISSUE THREAD

**Issue by hellocatfood** [aconz2/blender-addon-origamify#1]
I've installed this addon but it's not showing up in the addons menu. I've tried installing it on 2.91.2 and a beta of 2.92.0 and it still doesn't show.

I've checked in the blender addons folder and the addon files are there, it just isn't loading them.

**Comment by hellocatfood** [comment]
I've found out why the addon isn't showing, which may also solve why it wasn't working for your youtube viewers.

I attempted to install the addon by downloading this repository as a .zip. I then used Blender to install the zip, which is the way users normally install addons. This doesn't seem to work.

It works if I install *only* the .py file. This might be useful to include in the readme

**Comment by aconz2** [comment]
Gotcha, added to readme. Thanks for the info!
