### ISSUE TITLE
Not working with a certain shape

### ISSUE THREAD

**Issue by Graham91** [aconz2/blender-addon-origamify#2]
This shape simply wont origamify I cant figure out why. 
https://youtu.be/A55Sbx3aT1M
I can send you the blend file I show here in the video But I've been trouble shooting this all day. I have found that If you use limited dissolve it will work but limited dissolve causes other issues, if they are not triangles they no longer connect correctly.  Do you understand the error I am receiving?

**Comment by aconz2** [comment]
I was aware that error might crop up, but hadn't seen it in my own work. Looking back at the code now I'm not sure why I was using the method that I did, so I simplified it and have pushed an update. Try that out and see if it works

**Comment by Graham91** [comment]
Well that fixed one issue but brought up another. https://youtu.be/-GQOQi55j_8

**Comment by aconz2** [comment]
Hmm any transforms on the mesh? Shape keys? Can you send that mesh? Either blendfile or stl

**Comment by Graham91** [comment]
https://drive.google.com/file/d/1NQNgrKk5fP9KYJGXxSmiU7mOH4HFaIY6/view?usp=sharing 
Several of these objects are not working the one I showed you was chick.020.

Heres a script that flattens all objects in model. might help with testing.
https://drive.google.com/file/d/143srxETrsT1Zo9s7JcAjhd24cSXxZJdB/view?usp=sharing

**Comment by aconz2** [comment]
Now I've remembered why I was using that method and have made an update that corrects the flattening behavior. Test it out!

**Comment by Graham91** [comment]
This seems to be working well no issues. Thanks a ton!

**Comment by aconz2** [comment]
If things are working lets close the issue. If you run into anything else just open a new one

**Comment by Graham91** [comment]
Absolutely! Sorry I didn't realize that was my job, still learning:) thanks
