### ISSUE TITLE
Unable to use script

### ISSUE THREAD

**Issue by clefd** [aconz2/blender-addon-origamify#3]
I am unable to use the following script for blender3d (4.0).
https://github.com/aconz2/blender-addon-origamify
I followed the READ ME file but was still unable to use it. Could you assist?

**Comment by aconz2** [comment]
Should work fine in 4.0, I thought you might have hit an issue in 4.2, but it sounds like you just aren't able to install it. See https://docs.blender.org/manual/en/latest/editors/preferences/addons.html and https://github.com/aconz2/blender-addon-origamify?tab=readme-ov-file#installation

**Comment by clefd** [comment]
It's still not working for me after following the above steps. I have installed Add-Ons before like the blenderkit addon. But for some reason, this doesn't appear on the add-ons list after installing.

**Comment by clefd** [comment]
Hi. I tried it again using the zip file and it worked. I think I downloaded it incorrectly the first time. There was some syntax error coming in the code before. Now it's working. Thanks for this excellent tool. Cheers.
